# Generated by Django 5.0.4 on 2025-12-12 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Forum section',
                'verbose_name_plural': 'Forum sections',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=150)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('region', models.CharField(choices=[('temperate', 'Temperate'), ('tropical', 'Tropical'), ('desert', 'Desert'), ('mediterranean', 'Mediterranean'), ('other', 'Other')], max_length=20)),
                ('founding_mode', models.CharField(choices=[('claustral', 'Fully claustral'), ('semi_claustral', 'Semi claustral'), ('parasitic', 'Parasitic'), ('dependent', 'Dependent')], max_length=20)),
                ('diapause', models.CharField(choices=[('required', 'Requires diapause'), ('light', 'Light diapause'), ('none', 'No diapause')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='species_thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['genus', 'species'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='guide.forumsection')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='guide.species')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='guide.forumthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('favorite_region', models.CharField(blank=True, max_length=100)),
                ('receive_email_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NuptialFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='guide.species')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_min_c', models.PositiveIntegerField()),
                ('temperature_max_c', models.PositiveIntegerField()),
                ('humidity_min', models.PositiveIntegerField(help_text='As percent')),
                ('humidity_max', models.PositiveIntegerField(help_text='As percent')),
                ('diapause_notes', models.TextField()),
                ('founding_setup', models.TextField()),
                ('small_colony_setup', models.TextField()),
                ('medium_colony_setup', models.TextField()),
                ('large_colony_setup', models.TextField()),
                ('diet', models.TextField()),
                ('common_issues', models.TextField(blank=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care', to='guide.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_genus', models.CharField(max_length=100)),
                ('proposed_species', models.CharField(blank=True, max_length=100)),
                ('proposed_common_name', models.CharField(blank=True, max_length=150)),
                ('care_notes', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='guide.species')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('formicarium', 'Formicariums'), ('heating', 'Heating'), ('tools', 'Tools'), ('queens', 'Legal queen sellers'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_trusted', models.BooleanField(default=True)),
                ('species', models.ManyToManyField(blank=True, related_name='vendors', to='guide.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='guide.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'species')},
            },
        ),
    ]
